#!/bin/bash
# Basic git commands.


# Config
function configOwner {
  # get repo user or organization
  [ -z "$OWNER" ] && {
    OWNER=$(basename $(dirname `git ls-remote --get-url`))
    echo "${OWNER//*:/}" # If path has :owner, remove everything up to :.
  } || {
    echo $OWNER
  }
}
function configRepo {
  # get repo name
  [ -z "$REPO" ] && {
    echo $(basename -s .git `git ls-remote --get-url`)
  } || {
    echo $REPO
  }
}
function configBranch {
  # get branch name
  git branch --show-current
}
function configRoot {
  # get project root
  [ -z "$ROOT" ] && {
    echo $(git rev-parse --show-toplevel)
  } || {
    echo $ROOT
  }
}

# Check for unclean branch; ignore untracked files
function status {
  git status -s -uno
}

# git add w/ options and files
function add {
  local options="$@"
  git add $options
}

# git commit w/ message
function commit {
  local msg="$1"
  git commit -m "$msg"
}

# 4 Tag & Push
function tag {
  local msg="$1"
  local ver="$2"
  git tag -a -m "$msg" "$ver"
}

function push {
  git push --follow-tags
}

# Shepherd these functions.
source $(dirname "${0}")/sheep; sheep "$@"

