#!/bin/bash
# Gitea API Wrapper

function release {
  local tag="$1"
  local name="$2"
  local branch="$3"
  local body="$4"
  
  read -r -d '' content << EOF
    "body": "$body",
    "draft": false,
    "name": "$tag",
    "prerelease": false,
    "tag_name": "$tag",
    "target_commitish": "$branch"
EOF
  
  curl -L \
    --no-progress-meter \
    $GIT_API/repos/$OWNER/$REPO/releases \
    -H 'Accept: application/json' \
    -H "Authorization: Bearer $GIT_TOKEN" \
    -H 'Content-Type: application/json' \
    -d "{$content}"
}


# Shepherd these functions.
source $(dirname "${0}")/sheep; sheep "$@"

