#!/bin/bash
# Github API Wrapper

function release {
  local tag="$1"
  local name="$2"
  local branch="$3"
  local body=$4

  # default
  [ -z "$GIT_API" ] && { GIT_API="https://api.github.com"; }

  # Github doesn't like \n (new line) in the body of releases.
  body="${body//$'\n'/\\r\\n}"

  read -r -d '' content << EOF
    "tag_name": "$tag",
    "target_commitish": "$branch",
    "name": "$tag",
    "body": "$body",
    "draft": false,
    "prerelease": false,
    "generate_release_notes": false
EOF

  curl -L \
    --no-progress-meter \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer $GIT_TOKEN" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    $GIT_API/repos/$OWNER/$REPO/releases \
    -d "{$content}"
}


# Shepherd these functions.
source $(dirname "${0}")/sheep; sheep "$@"

